Add catastrophic backtracking detection to TravisCI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,6 +6,12 @@ python:
   - 2.7
 before_install:
   - |
+    grep -Pnr "([*+]|{\d+,\d*})\)([*+]|{\d+,\d*})" rules
+    if [[ $? -eq 0 ]]; then
+      echo "ERROR! Catastrophic backtracking has been detected and build has been aborted. See above." 
+      exit 1
+    fi
+  - |
     if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
       docker build --build-arg REPO=$TRAVIS_PULL_REQUEST_SLUG --build-arg COMMIT=$TRAVIS_PULL_REQUEST_SHA -t modsecurity-crs ./util/docker/
     else
